theme: jekyll-theme-minimal
title: "Mr. BT - IT Automation & Support Professional"
description: "Showcasing expertise in IT Service Management, ITIL best practices, and innovative software automation using Python, SQL, and top iPaaS tools."
url: "https://yourdomain.com"  # Replace with your custom domain or GitHub Pages URL
baseurl: ""  # Use a subpath if needed, e.g., /blog
author:
  name: "Mr. BT"
  email: "iammrbt+job@gmail.com"
  location: "Chesapeake, VA"
social:
  linkedin: "https://www.linkedin.com/in/brandonktaylor/"
markdown: kramdown
permalink: pretty

# Optional: Customize navigation or add additional plugins if needed
plugins: []
